# Generated by Django 5.0.4 on 2024-04-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('place_name', models.CharField(max_length=35, verbose_name='Название')),
                ('total_purchases', models.PositiveIntegerField(default=0, verbose_name='Количество покупок')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Средний чек')),
                ('total_nds', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма НДС')),
                ('total_tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма чаевых')),
            ],
            options={
                'verbose_name': 'Аналитика по месту покупки',
                'verbose_name_plural': 'Аналитика по местам покупок',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма потраченная на категорию за промежуток времени')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Средний чек по категории')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.place', verbose_name='Место покупки')),
            ],
            options={
                'verbose_name': 'Аналитика по категории',
                'verbose_name_plural': 'Аналитика по категориям',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'place'), name='Unique name and place'),
        ),
    ]
