# Generated by Django 5.0.4 on 2024-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_json', models.JSONField(verbose_name='Чек')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Посчитан')),
            ],
            options={
                'verbose_name': 'Чек для аналитики',
                'verbose_name_plural': 'Чеки для аналитики',
            },
        ),
    ]
